### ISSUE TITLE
Master Plan

### ISSUE THREAD

**Issue by kordianbruck** [MusicConnectionMachine/VisualizationG6#72]
So, to make this project awesome and help you guys to have a easy list of what needs to be done to complete this project we discussed and decided on the following. Your work until now is solid and presentable - we want to make it awesome :sparkles: :sparkles: :sparkles: 

- [x] #67 Implement Head Bar & Footer
- [x] #68 Add version & copyright
- [x] #69 Static pages
- [x] #73 About Page 
- [x] #55 Integrate Widgets
- [x] #70 Refactor start page
- [x] #71 Integrate search via API

Please start working on those issues from top to bottom. I or other tutors will update this issue with other tasks once we progress. Thanks a lot! We can do this easily if we pull through :tada:

**Comment by kordianbruck** [comment]
Done.
